version: '3.8'

services:
  frontend:
    build:
      context: ./libraryFrontend/docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./library/docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library_Container
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql

ysql:
    image: mysql:8.0
    container_name: library_Container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: library_Container
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local